### ISSUE TITLE
Fail to test Getx Middleware 

### ISSUE THREAD

**Issue by mwangaben** [cyenite/getx_test#1]
middleware code 

        import 'package:flutter/material.dart';
        import 'package:get/get.dart';
        import 'package:todoui/routes/index.dart';
        
        class FirstMiddleware extends GetMiddleware {
          final auth = false;
        
          @override
          int? get priority => 2;
        
          @override
          RouteSettings? redirect(String? route) {
            print('this is a route $route');
            if (auth == false) {
              return RouteSettings(name: AppRoutes.login);
            }
        
            return super.redirect(route);
          }
        }

Routes code 

        class AppRoutes {
  
              static String home = '/';
              static String login = '/login';
              static String health = '/health';
          
             static getHome() => home;
             static getLogin() => login;
             static getHealth() => health;
  
            static List<GetPage> routes = [
                    GetPage(page: () => const HomePage(), name: home),
                    GetPage(page: () => LoginPage(), name: login),
                    GetPage(page: () => HealthPage(), name: health, middlewares: [
                          FirstMiddleware(),
                        ]),
              
  
         }

testing code

        import 'package:flutter_test/flutter_test.dart';
        import 'package:get/get.dart';
        import 'package:getx_test/getx_test.dart';
        import 'package:todoui/routes/index.dart';
        
        void main() {
          getTest('testing route middleware', widgetTest: (tester) async {
            Get.toNamed(AppRoutes.health);
        
            expectLater('/login', Get.currentRoute);
          });
        }

Te test fail but it should pass since the middleware will redirect to login route as per Middleware code

**Comment by cyenite** [comment]
> middleware code
> 
> ```
>     import 'package:flutter/material.dart';
>     import 'package:get/get.dart';
>     import 'package:todoui/routes/index.dart';
>     
>     class FirstMiddleware extends GetMiddleware {
>       final auth = false;
>     
>       @override
>       int? get priority => 2;
>     
>       @override
>       RouteSettings? redirect(String? route) {
>         print('this is a route $route');
>         if (auth == false) {
>           return RouteSettings(name: AppRoutes.login);
>         }
>     
>         return super.redirect(route);
>       }
>     }
> ```
> 
> Routes code
> 
> ```
>     class AppRoutes {
> 
>           static String home = '/';
>           static String login = '/login';
>           static String health = '/health';
>       
>          static getHome() => home;
>          static getLogin() => login;
>          static getHealth() => health;
> 
>         static List<GetPage> routes = [
>                 GetPage(page: () => const HomePage(), name: home),
>                 GetPage(page: () => LoginPage(), name: login),
>                 GetPage(page: () => HealthPage(), name: health, middlewares: [
>                       FirstMiddleware(),
>                     ]),
>           
> 
>      }
> ```
> 
> testing code
> 
> ```
>     import 'package:flutter_test/flutter_test.dart';
>     import 'package:get/get.dart';
>     import 'package:getx_test/getx_test.dart';
>     import 'package:todoui/routes/index.dart';
>     
>     void main() {
>       getTest('testing route middleware', widgetTest: (tester) async {
>         Get.toNamed(AppRoutes.health);
>     
>         expectLater('/login', Get.currentRoute);
>       });
>     }
> ```
> 
> Te test fail but it should pass since the middleware will redirect to login route as per Middleware code

@mwangaben, the test fail could be because you are navigating to the '/health' route instead of '/login'. 

Your main function should be:

```
void main() {
  getTest('testing route middleware', widgetTest: (tester) async {
    Get.toNamed(AppRoutes.login);

    expectLater('/login', Get.currentRoute);
  });
}
```

**Comment by cyenite** [comment]
@mwangaben, for the expectLater to work you need to await the navigation.

i.e., modifying your test code like below passed the tests:

```
void main() {
  getTest('testing route middleware', widgetTest: (tester) async {
    await Get.toNamed(AppRoutes.health);

    expectLater('/login', Get.currentRoute);
  });
}

```

**Comment by mwangaben** [comment]
Thanks alot, what i have learnt is i had to await the navigation even if i use expect(.....)

    void main() {
        getTest('testing route middleware', widgetTest: (tester) async {
          await Get.toNamed(AppRoutes.health);
      
          expect('/login', Get.currentRoute);
        });
    }
